//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Astrila.Blank.Clients.RecipeBook.SyncServerWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BlankWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BlankWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PostFeedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BlankWebService() {
            this.Url = "http://localhost/BlankServer/BlankWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PostFeedCompletedEventHandler PostFeedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PostResult PostFeed(System.Xml.XmlNode feedDocument) {
            object[] results = this.Invoke("PostFeed", new object[] {
                        feedDocument});
            return ((PostResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostFeed(System.Xml.XmlNode feedDocument, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostFeed", new object[] {
                        feedDocument}, callback, asyncState);
        }
        
        /// <remarks/>
        public PostResult EndPostFeed(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PostResult)(results[0]));
        }
        
        /// <remarks/>
        public void PostFeedAsync(System.Xml.XmlNode feedDocument) {
            this.PostFeedAsync(feedDocument, null);
        }
        
        /// <remarks/>
        public void PostFeedAsync(System.Xml.XmlNode feedDocument, object userState) {
            if ((this.PostFeedOperationCompleted == null)) {
                this.PostFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostFeedOperationCompleted);
            }
            this.InvokeAsync("PostFeed", new object[] {
                        feedDocument}, this.PostFeedOperationCompleted, userState);
        }
        
        private void OnPostFeedOperationCompleted(object arg) {
            if ((this.PostFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostFeedCompleted(this, new PostFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PostResult {
        
        private System.DateTime sendMoreItemsUpdatedAfterField;
        
        private int totalItemsUpdatedField;
        
        private int totalItemsExaminedField;
        
        /// <remarks/>
        public System.DateTime SendMoreItemsUpdatedAfter {
            get {
                return this.sendMoreItemsUpdatedAfterField;
            }
            set {
                this.sendMoreItemsUpdatedAfterField = value;
            }
        }
        
        /// <remarks/>
        public int TotalItemsUpdated {
            get {
                return this.totalItemsUpdatedField;
            }
            set {
                this.totalItemsUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public int TotalItemsExamined {
            get {
                return this.totalItemsExaminedField;
            }
            set {
                this.totalItemsExaminedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void PostFeedCompletedEventHandler(object sender, PostFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591